[entryPoints]
  [entryPoints.web]
  address = ":80"
  [entryPoints.web-sercured]
  adress = ":443"


[api]
  dashboard = true
  debug = false
  insecure = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[certificatesResolvers.myresolver.acme]
  email = "me@example.com" 
  storage = "acme.json"
   [certificatesResolvers.myresolver.acme.httpChallenge]
     entryPoint = "web-secured"
     OnHostRule = true
  
