[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[api]
  dashboard = true
  debug = false
  insecure = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false

[acme]
email = "me@example.com"
storage = "acme.json"
entryPoint = "http"
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
