version: '3.3'

services:
 prometheus:
  container_name: prometheus
  image: prom/prometheus:v2.1.0
  volumes:
    - ./prometheus/:/etc/prometheus/
    - prometheus_data:/prometheus
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
  ports:
    - 9090:9090
  restart: always
  networks:
    - mynet

 alertmanager:
      container_name: alertmanager
      image: prom/alertmanager
      ports:
        - 9093:9093
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/alertmanager'
  
 node-exporter:
      container_name: node-exporter
      image: prom/node-exporter
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
      ports:
        - 9100:9100
      networks:
        - mynet
  
 cadvisor:
      container_name: cadvisor
      image: google/cadvisor:latest
      ports:
        - '8080:8080'
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      networks:
        - mynet
  
 grafana:
      container_name: grafana
      image: grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
      restart: always
      networks:
        - mynet
      environment:
        - GF_SERVER_DOMAIN="127.0.0.1"
        - GF_SERVER_ROOT_URL=%(protocol)s://192.168.5.12:3000
        - GF_SERVER_SERVE_FROM_SUB_PATH="true"
        - GF_SESSION_COOKIE_SECURE="false"
        
networks:
  mynet:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: